trigger: none

stages:
- stage: Build
  displayName: Build1 stage
  jobs:  
  - job: Build
    displayName: Build job
    pool: default
    steps:
    - script: echo Hello, world! This is CI job
      displayName: 'Run a one-line script'

    - task: PublishPipelineArtifact@0
      displayName: Create Artifact
      inputs:
        artifactName: Artifact1
        targetPath: Test

  - job: Build2
    displayName: Build2 job
    pool: default
    steps:
      - script: echo Hello, world! This is CI job
        displayName: 'Run a one-line script'

      - task: PublishPipelineArtifact@0
        displayName: Create Artifact
        inputs:
          artifactName: Artifact10
          targetPath: Test

- stage: Deploy
  displayName: Deploy stage
  jobs:
  - deployment: Deploy2
    displayName: Deploy2 job
    pool: default
    environment: NiadakEnvironment01
    strategy:
        runOnce:
          preDeploy:
            steps:
              - script: echo Hello, world! This is pre-deploy
                displayName: 'Run a one-line script'
              - powershell: sleep(300)
          deploy:
            steps:
            - script: echo Hello, world! This is deploy
              displayName: 'Run a one-line script' 

          routeTraffic:
            steps:
              - script: echo Hello, world! This is routeTraffic
                displayName: 'Run a one-line script'

          postRouteTraffic:
            steps:
              - script: echo Hello, world! This is postRouteTraffic
                displayName: 'Run a one-line script'
              - powershell: sleep(300)

          on:
            failure:
              steps:
              - script: echo Hello, world! This is on failure
                displayName: 'Run a one-line script'

            success:
              steps:
              - script: echo Hello, world! This is on success
                displayName: 'Run a one-line script'

  - deployment: VMDeploy
    displayName: web
    environment:
      name: Environment02
      resourceType: VirtualMachine
    strategy:
      rolling:
        maxParallel: 1
        preDeploy:
          steps:
            - script: echo Hello, world! This is pre-deploy
              displayName: 'Run a one-line script'
        deploy:
          steps:
          - script: echo Hello, world! This is deploy
            displayName: 'Run a one-line script' 

        routeTraffic:
          steps:
            - script: echo Hello, world! This is routeTraffic
              displayName: 'Run a one-line script'
            - powershell: sleep(300)

        postRouteTraffic:
          steps:
            - script: echo Hello, world! This is postRouteTraffic
              displayName: 'Run a one-line script'

        on:
          failure:
            steps:
            - script: echo Hello, world! This is on failure
              displayName: 'Run a one-line script'

          success:
            steps:
            - script: echo Hello, world! This is on success
              displayName: 'Run a one-line script'
