stages:
# - stage: Build
#   displayName: Build stage
#   jobs:  
#   - job: Build
#     displayName: Build job
#     pool: niadak
#     steps:
#     - script: echo Hello, world! This is CI job
#       displayName: 'Run a one-line script'

    # - task: PublishPipelineArtifact@0
    #   displayName: Create Artifact
    #   inputs:
    #     artifactName: Artifact1
    #     targetPath: Test

    # - upload: Sample-pipeline.yaml
    #   artifact: Artifact2

- stage: Deploy
  displayName: Deploy stage
  jobs:  
  - deployment: Deploy
    displayName: Deploy job
    pool: niadak
    environment: NiadakEnvironment01
    strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self
              - script: echo Hello, world! This is deploy job
                displayName: 'Run a one-line script'
              - powershell: ls $(Pipeline.Workspace) -r #Check the content of the workspace directory
                displayName: Explore workspace

              - task: PublishPipelineArtifact@0
                displayName: Create Artifact
                inputs:
                  artifactName: Artifact1
                  targetPath: Test

  # - deployment: Deploy2
  #   displayName: Deploy2 job
  #   pool: niadak
  #   environment: NiadakEnvironment01
  #   strategy:
  #       runOnce:
  #         deploy:
  #           steps:
  #             - script: echo Hello, world! This is deploy job
  #               displayName: 'Run a one-line script'
  #             - powershell: ls $(Pipeline.Workspace) -r #Check the content of the workspace directory
  #               displayName: Explore workspace

  # - deployment: Deploy3
  #   displayName: Deploy3 job
  #   pool: niadak
  #   environment: NiadakEnvironment01
  #   strategy:
  #       runOnce:
  #         deploy:
  #           steps:
  #             - script: echo Hello, world! This is deploy job
  #               displayName: 'Run a one-line script'
  #             - powershell: ls $(Pipeline.Workspace) -r #Check the content of the workspace directory
  #               displayName: Explore workspace

  # - deployment: Deploy4
  #   displayName: Deploy4 job
  #   pool: niadak
  #   environment: NiadakEnvironment01
  #   strategy:
  #       runOnce:
  #         deploy:
  #           steps:
  #             - script: echo Hello, world! This is deploy job
  #               displayName: 'Run a one-line script'
  #             - powershell: ls $(Pipeline.Workspace) -r #Check the content of the workspace directory
  #               displayName: Explore workspace


