stages:
- stage: Build
  displayName: Build1 stage
  jobs:  
  - job: Build
    displayName: Build job
    pool: niadak
    steps:
    - script: echo Hello, world! This is CI job
      displayName: 'Run a one-line script'

    - task: PublishPipelineArtifact@0
      displayName: Create Artifact
      inputs:
        artifactName: Artifact1
        targetPath: Test

- stage: Deploy
  displayName: Deploy stage
  jobs:
  - deployment: Deploy
    displayName: Deploy job
    variables:
    - group: Niadak-VG-01
    pool: niadak
    environment: NiadakEnvironment01
    strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self
              - script: echo Hello, world! This is deploy job
                displayName: 'Run a one-line script'

              - upload: DownloadArtifact-validation-Pipeline.Yaml
                artifact: Artifact2

  - deployment: Deploy2
    displayName: Deploy2 job
    pool: niadak
    environment: NiadakEnvironment01
    strategy:
        runOnce:
          deploy:
            steps:
            - script: echo Hello, world! This is CI job
              displayName: 'Run a one-line script'

            - task: PublishPipelineArtifact@0
              displayName: Create Artifact
              inputs:
                artifactName: Artifact1
                targetPath: Test
