stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build job
    pool: niadak
    steps:
    - script: echo Hello, world! This is CI job
      displayName: 'Run a one-line script'

    - task: PublishPipelineArtifact@0
      displayName: Create Artifact
      inputs:
        artifactName: Artifact1
        targetPath: Test

    - upload: Sample-pipeline.yaml
      artifact: Artifact2

- stage: Deploy
  displayName: Deploy stage
  jobs:  
  - deployment: Deploy
    displayName: Deploy job
    pool: niadak
    environment: NiadakEnvironment01
    strategy:
        runOnce:
          deploy:
            steps:
              - checkout: abc
              - script: echo Hello, world! This is deploy job
                displayName: 'Run a one-line script'
              - powershell: ls $(Pipeline.Workspace) -r #Check the content of the workspace directory
                displayName: Explore workspace

              - powershell: |
                  Remove-Item $(Pipeline.Workspace)\Artifact1 -Recurse -Force
                  Remove-Item $(Pipeline.Workspace)\Artifact2 -Recurse -Force
                displayName: Scorch workspace

              - task: PublishPipelineArtifact@0
                displayName: Create Artifact
                inputs:
                  artifactName: AzCopy
                  targetPath: azcopy

  # - deployment: Deploy2
  #   displayName: Deploy2 job
  #   pool: niadak
  #   environment: NiadakEnvironment01
  #   strategy:
  #       runOnce:
  #         deploy:
  #           steps:
  #             - script: echo Hello, world! This is deploy job
  #               displayName: 'Run a one-line script'
  #             - powershell: ls $(Pipeline.Workspace) -r #Check the content of the workspace directory
  #               displayName: Explore workspace

  #             - powershell: |
  #                 Remove-Item $(Pipeline.Workspace)\Artifact1 -Recurse -Force
  #                 Remove-Item $(Pipeline.Workspace)\Artifact2 -Recurse -Force
  #               displayName: Scorch workspace

  #             - task: PublishPipelineArtifact@0
  #               displayName: Create Artifact
  #               inputs:
  #                 artifactName: AzCopy
  #                 targetPath: azcopy

  # - deployment: Deploy3
  #   displayName: Deploy3 job
  #   pool: niadak
  #   environment: NiadakEnvironment01
  #   strategy:
  #       runOnce:
  #         deploy:
  #           steps:
  #             - script: echo Hello, world! This is deploy job
  #               displayName: 'Run a one-line script'
  #             - powershell: ls $(Pipeline.Workspace) -r #Check the content of the workspace directory
  #               displayName: Explore workspace

  #             - powershell: |
  #                 Remove-Item $(Pipeline.Workspace)\Artifact1 -Recurse -Force
  #                 Remove-Item $(Pipeline.Workspace)\Artifact2 -Recurse -Force
  #               displayName: Scorch workspace

  #             - task: PublishPipelineArtifact@0
  #               displayName: Create Artifact
  #               inputs:
  #                 artifactName: AzCopy
  #                 targetPath: azcopy

