trigger: none
stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build job
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project $(system.accesstoken)
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'

- stage: Deploy
  displayName: Deploy stage
  jobs:  
  - deployment: Deploy
    displayName: Deploy job
    environment: NiadakEnvironment01
    strategy:
        runOnce:
          deploy:
            steps:
            - script: |
                echo Add other tasks to build, test, and deploy your project $(system.accesstoken)
                echo See https://aka.ms/yaml
            - powershell: throw "kdjskljkls"
              displayName: 'Run a multi-line script'

