
trigger: none
stages:
- stage: Deploy
  displayName: Deploy stage
  jobs:  
  - job: Build
    strategy:
      matrix:
        Python35:
          PYTHON_VERSION: '3.5'
        Python36:
          PYTHON_VERSION: '3.6'
    steps:
      - script: echo Hello, world! This is pre-deploy
        displayName: 'Run a one-line script'

  - deployment: Deploy
    displayName: Deploy job
    #pool: default
    environment: NiadakEnvironment01
    strategy:
      runOnce:
        preDeploy:
          steps:
            - script: echo Hello, world! This is pre-deploy
              displayName: 'Run a one-line script'
        deploy:
          steps:
            - script: echo Hello, world! This is deploy
              displayName: 'Run a one-line script'

        routeTraffic:
          steps:
            - script: echo Hello, world! This is routeTraffic
              displayName: 'Run a one-line script'

        postRouteTraffic:
          steps:
            - script: echo Hello, world! This is postRouteTraffic
              displayName: 'Run a one-line script'

        on:
          failure:
            steps:
            - script: echo Hello, world! This is on failure
              displayName: 'Run a one-line script'

          success:
            steps:
            - script: echo Hello, world! This is on success
              displayName: 'Run a one-line script'

