trigger: none
stages:
- stage: Deploy
  displayName: Deploy stage
  jobs:  
  - deployment: Deploy
    displayName: Deploy job
    environment: NiadakEnvironment01
    pool:
      vmImage: 'vs2017-win2016'
    strategy:
        runOnce:
          deploy:
            steps:
            - script: |
                echo Add other tasks to build, test, and deploy your project $(system.accesstoken)
                echo See https://aka.ms/yaml
              displayName: 'Run a multi-line script'

