trigger: none
stages:
- stage: Deploy
  displayName: Deploy stage
  jobs:
  - job: CI
    steps:
    - script: echo Hello, world! This is CI
      displayName: 'Run a one-line script'

  - deployment: Deploy
    displayName: Deploy job
    environment: NiadakEnvironment01
    #pool: Default
    strategy:
        runOnce:
          deploy:
            steps:
            - script: echo Hello, world! This is deploy
              displayName: 'Run a one-line script'
