stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build job
    pool:
      name: niadak
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project $(system.jobid), $(system.jobName), $(system.jobDisplayName), $(system.definitionName).
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'

- stage: Deploy
  displayName: Deploy stage
  jobs:  
  - deployment: Deploy
    displayName: Deploy job
    pool:
      name: niadak
    environment: NiadakEnvironment01
    strategy:
        runOnce:
          deploy:
            steps:
            - download: none
            - script: echo Hello, world! This is deploy job $(system.jobid), $(system.jobName), $(system.jobDisplayName), $(system.definitionName)
              displayName: 'Run a one-line script'
