trigger: none
stages:
- stage: Deploy
  displayName: Deploy stage
  jobs:  
  - deployment: Deploy
    displayName: Deploy job
    environment: NiadakEnvironment01
    pool:
      vmImage: 'ubuntu-18.04'
    strategy:
        runOnce:
          deploy:
            steps:
            - task: Xcode@5
              inputs:
                actions: 'build'
                packageApp: false
