trigger: none
stages:
- stage: Deploy
  displayName: Deploy stage
  jobs:  
  - deployment: Deploy
    displayName: Deploy job
    environment: NiadakEnvironment01
    pool: Hosted VS2017
    #  vmImage: 'vs2017-win2016'
    strategy:
        runOnce:
          deploy:
            steps:
            - task: Xcode@5
              inputs:
                actions: 'build'
                packageApp: false
