trigger: none
stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build job
    pool:
      name: niadak
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project $(system.accesstoken)
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'

    - powershell: |
        $url = "$($env:SYSTEM_TEAMFOUNDATIONCOLLECTIONURI)$env:SYSTEM_TEAMPROJECTID/_apis/build/definitions/$($env:SYSTEM_DEFINITIONID)?api-version=4.1-preview"
        Write-Host "URL: $url"
        $pipeline = Invoke-RestMethod -Uri $url -Headers @{
          Authorization = "Bearer $(system.accesstoken)"
        }
        Write-Host "Pipeline = $($pipeline | ConvertTo-Json -Depth 100)"

- stage: Deploy
  displayName: Deploy stage
  jobs:  
  - deployment: Deploy
    displayName: Deploy job
#    pool:
#      name: niadak
    environment: NiadakEnvironment01
    strategy:
        runOnce:
          deploy:
            steps:
            - download: none
            - script: echo Hello, world! This is deploy job $(system.accesstoken)
              displayName: 'Run a one-line script'

            - powershell: |
                $url = "$($env:SYSTEM_TEAMFOUNDATIONCOLLECTIONURI)$env:SYSTEM_TEAMPROJECTID/_apis/build/definitions/$($env:SYSTEM_DEFINITIONID)?api-version=4.1-preview"
                Write-Host "URL: $url"
                $pipeline = Invoke-RestMethod -Uri $url -Headers @{
                  Authorization = "Bearer $(system.accesstoken)"
                }
                Write-Host "Pipeline = $($pipeline | ConvertTo-Json -Depth 100)"
